input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [spring_application_name] {
    mutate {
      add_field => { "service_name" => "%{spring_application_name}" }
    }
  }

  if [timestamp] {
    mutate {
      rename => { "timestamp" => "app_timestamp" }
    }
  }

  if [level] {
    mutate {
      uppercase => [ "level" ]
    }
  }

  mutate {
    remove_field => [ "host", "port", "@version" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "hk-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
