apiVersion: v1
kind: ConfigMap
metadata:
  name: hk-fintech-config
  namespace: hk-fintech
  labels:
    app.kubernetes.io/part-of: hk-fintech
data:
  IDENTITY_SERVICE_URL: "http://identity-service:9090"
  WALLET_SERVICE_URL: "http://wallet-service:9091"
  CARD_SERVICE_URL: "http://card-service:9092"
  PAYMENT_SERVICE_URL: "http://payment-service:9093"
  INVOICE_SERVICE_URL: "http://invoice-service:9094"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  IDENTITY_DB_HOST: "postgres-identity"
  WALLET_DB_HOST: "postgres-wallet"
  CARD_DB_HOST: "postgres-card"
  PAYMENT_DB_HOST: "postgres-payment"
  INVOICE_DB_HOST: "postgres-invoice"
  DB_PORT: "5432"

  JWT_EXPIRATION: "86400000"
