apiVersion: v1
kind: Secret
metadata:
  name: hk-fintech-secret
  namespace: hk-fintech
  labels:
    app.kubernetes.io/part-of: hk-fintech-hk-fintech
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

  JWT_SECRET_KEY: NTM2NzU2NkI1OTcwMzM3MzM2NzYzOTc5MkY0MjNGNDUyODQ4MkI0RDYyNTE2NTU0Njg1NzZENUE3MTM0NzQzNw==
